
# Concordance mutation/drug

```{r}

library(targets)
library(data.table)

mut.inhib <- tar_read(tt_mut_assocs)

mut.inhib[train_fdr < .05 & sign(train_est) == sign(test_est),.N]#213
mut.inhib[train_fdr < .05,.N]#239

#213/239= 0.8912134

#same for expression



```

#concordance

```{r}

library(data.table)
library(targets)
library(broom)

clin <- tar_read(clin_data)
inhib <- tar_read(inhib_data)
wgcna.mes <- tar_read(wgcna_mes)
wgcna.maps <- tar_read(wgcna_maps)
  
use.inhib <- merge(clin[manuscript_inhibitor == "yes",.(ptid, cohort)], inhib[status == "train/test"], by="ptid")
  
mod.inhib.dt <- merge(wgcna.mes[,.(ptid, module, PC1)], use.inhib, by=c("ptid"), allow.cartesian=T)
  
exprs.inh.cor <- mod.inhib.dt[,tidy(cor.test(auc, PC1)),by=.(cohort, module, inhibitor)]
  
#assuming N is parameter + 2 requiring 30 patients
  
exprs.inh.cor <- exprs.inh.cor[parameter > 28]
  
cor.kme <- merge(wgcna.maps$mod.map[cur_labels != "M0"], exprs.inh.cor, by.x="cur_labels", by.y="module")
  
cor.kme[,titles:=paste0(sub("M", "Mod", cur_labels), " (", prev_modules, ")")]
  
cast.ck <- dcast(titles+inhibitor~cohort, value.var=c("estimate", "p.value"), data=cor.kme)
  
#as the pvalues seem to indicate a little too much dependency
cast.ck[,`fdr_Waves1+2`:=p.adjust(`p.value_Waves1+2`, method="BY")]
cast.ck[,`fdr_Waves3+4`:=p.adjust(`p.value_Waves3+4`, method="BY")]

#check against figure data
exprs.inhib <- tar_read(mod_drug_cor)

stopifnot(isTRUE(all.equal(exprs.inhib[order(titles, inhibitor),.(titles, inhibitor, `Waves1+2`, `Waves3+4`)], cast.ck[order(titles, inhibitor),.(titles, inhibitor, `Waves1+2`=`estimate_Waves1+2`, `Waves3+4`=`estimate_Waves3+4`)])))

cast.ck[`fdr_Waves1+2` < .05,.N]#219

cast.ck[`fdr_Waves1+2` < .05 & sign(`estimate_Waves1+2`) == sign(`estimate_Waves3+4`),.N]#214

```


# Sample size

```{r}

library(targets)
library(data.table)

samps <- data.table(openxlsx::read.xlsx(tar_read(clin_wkst)))

samps[cohort %in% c("Waves3+4","Both"),.N]#293
samps[cohort %in% c("Waves3+4","Both"),length(unique(dbgap_subject_id))]#279

wv.12.samps <- samps[cohort %in% c("Waves1+2","Both")]

wv.34.samps <- samps[cohort %in% c("Waves3+4","Both")]

only.wv.34 <- setdiff(wv.34.samps$dbgap_subject_id, wv.12.samps$dbgap_subject_id)

length(only.wv.34)#243 patients

samps[dbgap_subject_id %in% only.wv.34,.N]#255

samps[,.N] #942

samps[,.N,by=dbgap_subject_id][,.N]#805

samps[diseaseStageAtSpecimenCollection == "Initial Diagnosis",.N,by=dbgap_subject_id][,.N]#562

#562/805 = 0.6981366

clin <- samps[used_manuscript_analyses=="yes"]

clin.sum <- clin[,.SD[order(timeOfSampleCollectionRelativeToInclusion)][1],by=dbgap_subject_id]
  
stopifnot(clin.sum[,.N,by=dbgap_subject_id][,all(N==1)])
  
denovo.sum <- clin.sum[,.N,by=.(isDenovo, cohort)]

denovo.sum[,freq:=N/sum(N),by=cohort]
denovo.sum[isDenovo == "TRUE"]
#   isDenovo   cohort   N      freq
#1:     TRUE Waves1+2 247 0.4930140
#2:     TRUE Waves3+4 136 0.5811966


```

#PEAR1 vs ELN2017

```{r}

library(data.table)
library(targets)
library(broom)

p1.rna <- tar_read(p1_rna)

p1.rna <- p1.rna[is.na(age_cut)==F]

p1.rna[,age_cat:=as.character(age_cut)]
p1.rna[age_cut %in% c("older","oldest"), age_cat:="older+oldest"]
  
eln.res <- p1.rna[is.na(age_cut)==F & is.na(ELN2017)==F & ELN2017 != "Intermediate",cbind(as.data.table(tidy(t.test(PEAR1~ELN2017))),n=.N),by=age_cat][,.(age_cat, estimate, p.value, n)]

#         age_cat  estimate      p.value   n
# 1:       middle 1.4973583 6.326008e-03  72
# 2: older+oldest 3.7654968 3.276102e-25 172
# 3:        young 0.7623476 1.698327e-01  79

```

# PYCARD survival

```{r}

library(data.table)
library(targets)
library(survival)
library(broom)

exprs <- tar_read(comb_exprs)
clin <- tar_read(clin_data)

rna.clin <- clin[manuscript_rnaseq=="yes" & isDenovo == "TRUE" & is.na(overallSurvival)==F & is.na(isDead)==F]
  
py.dt <- cbind(rna.clin[,.(ptid, overallSurvival, isDead, age_cut)], exprs[rna.clin$ptid,"PYCARD",drop=F])

as.data.table(tidy(coxph(Surv(time=overallSurvival, event=isDead, type="right") ~PYCARD,data=as.data.frame(py.dt))))

#     term     estimate  std.error   statistic   p.value
#1: PYCARD -0.008479793 0.09543715 -0.08885212 0.9291994

as.data.table(tidy(coxph(Surv(time=overallSurvival, event=isDead, type="right") ~PYCARD,data=as.data.frame(py.dt[age_cut == "young"]))))

#     term  estimate std.error statistic   p.value
#1: PYCARD 0.1547743 0.3280003 0.4718725 0.6370178

```

# Survival by cohort stats

```{r}

library(targets)
library(data.table)
library(survival)

clin.sum <- tar_read(clin_sum)

over.wave.dt <- clin.sum[is.na(isDead)==F & is.na(overallSurvival)==F,.(ptid, isDead, overallSurvival, cohort)]
  
survdiff(Surv(time=overallSurvival, event=isDead, type="right") ~  cohort, data = as.data.frame(over.wave.dt), rho=0)

#                   N Observed Expected (O-E)^2/E (O-E)^2/V
# cohort=Waves1+2 491      310      320     0.335      1.32
# cohort=Waves3+4 214      120      110     0.978      1.32
# 
#  Chisq= 1.3  on 1 degrees of freedom, p= 0.2 

```

# Denovo inhibitors by wave

```{r}

library(targets)
library(data.table)
library(broom)

inhib.sum <- tar_read(inhib_sum)

as.data.table(broom::tidy(inhib.sum[,cor.test(`mean_Waves1+2`, `mean_Waves3+4`)]))
  
#     estimate statistic      p.value parameter  conf.low conf.high                               method alternative
# 1: 0.9651838  35.58436 5.856928e-56        93 0.9480639 0.9767278 Pearson's product-moment correlation   two.sided

```


# PEAR1 Averages for ethnicity

```{r}

library(targets)
library(data.table)
library(broom)

clin <- tar_read(clin_data)
p1.dt <- tar_read(p1_rna)

stopifnot(clin[is.na(inferred_ethnicity),all(cohort == "Waves3+4")])

clin[is.na(reportedEthnicity), reportedEthnicity:="UNKNOWN"]
clin[is.na(reportedRace), reportedRace:="Unknown"]

clin[,consensus_ethnicity:=inferred_ethnicity]
clin[is.na(consensus_ethnicity),consensus_ethnicity:=reportedRace]
clin[reportedEthnicity == "HISPANIC",consensus_ethnicity:="HispNative"]

clin[consensus_ethnicity == "American Indian", consensus_ethnicity:="HispNative"]
clin[consensus_ethnicity == "Pacific Islander", consensus_ethnicity:="Asian"]

p1.eth <- merge(p1.dt, clin[manuscript_rnaseq=="yes" & diseaseStageAtSpecimenCollection == "Initial Diagnosis",.(ptid, consensus_ethnicity)], by="ptid")

p1.eth[,.(mean_pear=round(mean(PEAR1), 3),.N),by=consensus_ethnicity]

#    consensus_ethnicity mean_pear   N
# 1:               White     1.395 359
# 2:               Black     2.205  13
# 3:               Asian     1.924  15
# 4:          HispNative     1.863  31
# 5:        AdmixedBlack     1.954   1
# 6:        AdmixedWhite     1.514   1
# 7:             Unknown     2.291  13
# 8:            Declined     0.238   2



```

# Average difference in mutation frequency

```{r}

library(data.table)
library(targets)

freqs <- tar_read(mut_freqs)

#for ASXL1
freqs[symbol == "ASXL1"]
#  symbol train_prop test_prop  max_prop symb_ord       diff
#1:  ASXL1 0.08713693 0.1515152 0.1515152    ASXL1 0.06437822

round(freqs[,mean(diff)]*100, 3)#1.321

```


# PEAR1 by denovo vs transformed

```{r}

library(data.table)
library(targets)
library(broom)

clin <- tar_read(clin_data)
p1.dt <- tar_read(p1_rna)
vg.scores <- tar_read(vg_scores)

rna.clin <- clin[manuscript_rnaseq=="yes" & diseaseStageAtSpecimenCollection == "Initial Diagnosis"]
  
rcp <- merge(p1.dt[,.(ptid, PEAR1)], rna.clin, by="ptid")
  
mlt.type <- suppressWarnings(melt(rcp, measure.vars=c("isDenovo", "isTransformed", "isTherapy"), id.vars=c("ptid", "cohort" ,"PEAR1"), variable.factor=F))
mlt.sum <- mlt.type[value %in% c("TRUE"),.(type=paste(unique(variable), collapse=";")), by=.(ptid, cohort, PEAR1)]
#only a couple
mlt.sum <- mlt.sum[grepl(";", type)==F]
  
vg.sum <- merge(vg.scores$summary[,.(ptid, vg_type, cohort, PC1)], mlt.sum[type %in% c("isDenovo", "isTransformed")], by=c("ptid", "cohort"))
  
vg.sum[,cats:=ifelse(type=="isDenovo","Denovo", "Transformed")]
  
hsc.sum <- vg.sum[vg_type %in% c("HSC-like", "Monocyte-like")]

as.data.table(tidy(lm(PEAR1~PC1*cats, data=hsc.sum[vg_type == "HSC-like"])))
#                   term  estimate  std.error statistic      p.value
# 1:         (Intercept) 1.3590273 0.11277803 12.050462 2.099174e-28
# 2:                 PC1 0.5107280 0.04606156 11.087942 7.774774e-25
# 3:     catsTransformed 0.9151754 0.30474099  3.003125 2.855420e-03
# 4: PC1:catsTransformed 0.2597414 0.11473769  2.263784 2.417062e-02


as.data.table(tidy(lm(PEAR1~PC1*cats, data=hsc.sum[vg_type == "Monocyte-like"])))
#                   term    estimate  std.error  statistic      p.value
# 1:         (Intercept)  1.20425037 0.13566992  8.8763257 3.099431e-17
# 2:                 PC1  0.05471832 0.03140290  1.7424609 8.226548e-02
# 3:     catsTransformed  1.80242643 0.35339519  5.1003140 5.447135e-07
# 4: PC1:catsTransformed -0.05980337 0.09226512 -0.6481689 5.172811e-01
```


#LSC17 by denovo vs transformed

```{r}

library(data.table)
library(targets)
library(broom)

clin <- tar_read(clin_data)

lsc17 <- tar_read(lsc17)

rna.clin <- clin[manuscript_rnaseq=="yes" & diseaseStageAtSpecimenCollection == "Initial Diagnosis"]
  
rcp <- merge(lsc17, rna.clin, by="ptid")
  
mlt.type <- suppressWarnings(melt(rcp, measure.vars=c("isDenovo", "isTransformed", "isTherapy"), id.vars=c("ptid", "cohort" ,"LSC17"), variable.factor=F))
mlt.sum <- mlt.type[value %in% c("TRUE"),.(type=paste(unique(variable), collapse=";")), by=.(ptid, cohort, LSC17)]
#only a couple
mlt.sum <- mlt.sum[grepl(";", type)==F]
  
devtra <- rbindlist(
    list(
      dtrans=data.table(tidy(t.test(LSC17~type,data=mlt.sum[type %in% c("isDenovo", "isTransformed")]))),
      dther=data.table(tidy(t.test(LSC17~type,data=mlt.sum[type %in% c("isDenovo", "isTherapy")])))
    ), idcol="type"
)

#     type    estimate estimate1 estimate2  statistic      p.value parameter   conf.low   conf.high                  method alternative
# 1: dtrans -0.26296959 0.3180931 0.5810627 -5.6778465 2.171146e-07  79.08198 -0.3551558 -0.17078333 Welch Two Sample t-test   two.sided
# 2:  dther -0.06857644 0.3180931 0.3866695 -0.8780281 3.863210e-01  32.76961 -0.2275202  0.09036733 Welch Two Sample t-test   two.sided

```
